# Generated by Django 6.0.6 on 2026-08-13 16:32

import django.db.models.deletion
import tv.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0018_region_email_region_location_region_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TVScreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Internal name, e.g. 'Reception TV — Caldas'", max_length=120)),
                ('slug', models.SlugField(default=tv.models.generate_screen_token, help_text='Hidden token used as the public URL. Regenerate to invalidate the old link.', max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quote_text', models.TextField(blank=True, default='Cuida deste espaço como cuidas de ti.', help_text='Quote shown under the clock')),
                ('quote_author', models.CharField(blank=True, default='YourSelf Pilates', max_length=120)),
                ('contact_phone', models.CharField(blank=True, max_length=40)),
                ('wifi_name', models.CharField(blank=True, max_length=120)),
                ('wifi_password', models.CharField(blank=True, max_length=120)),
                ('booking_url', models.URLField(blank=True, help_text="URL encoded in the QR code shown in the 'Agendar Online' card")),
                ('booking_cta_title', models.CharField(blank=True, default='Agendar Online', max_length=120)),
                ('booking_cta_subtitle', models.CharField(blank=True, default='Aponta a câmara do telemóvel para o QR code', max_length=200)),
                ('welcome_message_template', models.CharField(blank=True, default='Bem-vindo(a) {student}, desejamos-te um excelente treino!', max_length=255)),
                ('show_teacher_name', models.BooleanField(default=True)),
                ('refresh_interval_seconds', models.PositiveIntegerField(default=60, help_text='How often the screen re-checks the backend for the current booking')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(help_text='Gym region/location this screen belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='tv_screens', to='subscriptions.region')),
            ],
            options={
                'ordering': ['region__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TVTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Playback order, lowest first')),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('audio_file', models.FileField(upload_to='tv/music/')),
                ('artist', models.CharField(blank=True, max_length=255)),
                ('region', models.ForeignKey(help_text='Only screens of this region will play this item', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='subscriptions.region')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'uploaded_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TVVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Playback order, lowest first')),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('video_file', models.FileField(upload_to='tv/videos/')),
                ('description', models.TextField(blank=True, null=True)),
                ('caption', models.CharField(blank=True, help_text="Badge shown over the video, e.g. 'Inspiração em movimento'", max_length=160)),
                ('region', models.ForeignKey(help_text='Only screens of this region will play this item', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='subscriptions.region')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'uploaded_at'],
                'abstract': False,
            },
        ),
    ]
