# Generated by Django 6.0.6 on 2026-08-17 20:03

from django.db import migrations


def carry_footer_up_to_region(apps, schema_editor):
    """
    Move each screen's footer details onto its region before the columns go.

    A screen that was configured before Region grew these fields is the only
    place that text exists, so it is copied up rather than dropped — but never
    over a region that already says something of its own.
    """
    TVScreen = apps.get_model('tv', 'TVScreen')
    pairs = [
        ('contact_phone', 'phone'),
        ('wifi_name', 'wifi_name'),
        ('wifi_password', 'wifi_password'),
    ]

    for screen in TVScreen.objects.select_related('region'):
        region = screen.region
        changed = []
        for screen_field, region_field in pairs:
            value = getattr(screen, screen_field, '')
            if value and not getattr(region, region_field, ''):
                setattr(region, region_field, value)
                changed.append(region_field)
        if changed:
            region.save(update_fields=changed)


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0001_initial'),
        ('subscriptions', '0019_region_wifi_name_region_wifi_password'),
    ]

    operations = [
        migrations.RunPython(
            carry_footer_up_to_region,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='tvscreen',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='tvscreen',
            name='wifi_name',
        ),
        migrations.RemoveField(
            model_name='tvscreen',
            name='wifi_password',
        ),
    ]
