# Generated by Django 5.2.9 on 2025-12-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='total_hours',
            field=models.PositiveIntegerField(default=0, help_text='Total hours included in this pack'),
        ),
    ]
