# Generated by Django 5.2.9 on 2025-12-05 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_subscriptionhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(editable=False, max_length=25, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('multibanco', 'MultiBanco'), ('mbway', 'MB WAY'), ('creditcard', 'Credit Card')], max_length=20)),
                ('payment_status', models.CharField(choices=[('Pendente', 'Pendente'), ('Pago', 'Pago'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=20)),
                ('mb_key', models.CharField(blank=True, help_text='MB Key used (e.g., CWR-828507)', max_length=50, null=True)),
                ('mb_entity', models.CharField(blank=True, help_text='MultiBanco Entity', max_length=10, null=True)),
                ('mb_reference', models.CharField(blank=True, help_text='MultiBanco Reference', max_length=20, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, help_text='Payment expiry date', null=True)),
                ('request_id', models.CharField(blank=True, help_text='IfThenPay RequestId', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='subscriptions.pack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='subscriptionhistory',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Associated order for this subscription', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_records', to='subscriptions.order'),
        ),
    ]
