# Generated by Django 5.2.9 on 2025-12-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_order_subscriptionhistory_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mbway_phone',
            field=models.CharField(blank=True, help_text='Phone number for MB WAY (format: 351#912345678)', max_length=20, null=True),
        ),
    ]
