# Generated by Django 5.2.9 on 2025-12-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_order_mbway_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ccard_payment_url',
            field=models.URLField(blank=True, help_text='IfThenPay payment page URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='ccard_signature_key',
            field=models.CharField(blank=True, help_text='Signature key (sk) for verification', max_length=100, null=True),
        ),
    ]
