# Generated by Django 5.2.9 on 2025-12-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_order_ccard_payment_url_order_ccard_signature_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ccard_payment_url',
            field=models.URLField(blank=True, help_text='IfThenPay payment page URL', max_length=1000, null=True),
        ),
    ]
