# Generated by Django 5.2.9 on 2025-12-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_alter_order_ccard_payment_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ccard_payment_url',
            field=models.TextField(blank=True, help_text='IfThenPay payment page URL', null=True),
        ),
    ]
