# Generated by Django 5.2.9 on 2025-12-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_alter_order_ccard_payment_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique code (e.g., multibanco, mbway)', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Display name', max_length=50)),
                ('description', models.TextField(help_text='Short description')),
                ('icon', models.CharField(default='💳', help_text='Emoji icon', max_length=10)),
                ('payment_type', models.CharField(choices=[('reference', 'Reference-based'), ('instant', 'Instant'), ('redirect', 'Redirect')], help_text='Type of payment flow', max_length=20)),
                ('instructions', models.TextField(help_text='Instructions for users')),
                ('active', models.BooleanField(default=True, help_text='Is this payment method available?')),
                ('display_order', models.IntegerField(default=0, help_text='Order in which to display (lower = first)')),
                ('timeout_minutes', models.IntegerField(blank=True, help_text='Timeout in minutes (e.g., 4 for MB WAY)', null=True)),
                ('expiry_days', models.IntegerField(blank=True, help_text='Expiry days (e.g., 3 for MultiBanco)', null=True)),
                ('accepted_cards', models.CharField(blank=True, help_text='Comma-separated card types (for credit cards)', max_length=200)),
                ('requires_phone', models.BooleanField(default=False, help_text='Requires phone number?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
