# Generated by Django 5.2.9 on 2025-12-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method_updated_at',
            field=models.DateTimeField(blank=True, help_text='Last time payment method was changed', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='previous_payment_method',
            field=models.CharField(blank=True, help_text='Previous payment method before change', max_length=20, null=True),
        ),
    ]
