# Generated by Django 4.2.25 on 2026-03-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0011_merge_0010_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_datetime',
            field=models.DateTimeField(blank=True, help_text='Datetime reported by IfThenPay when payment was made', null=True),
        ),
    ]
