# Generated by Django 6.0.6 on 2026-06-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0012_order_payment_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='target_role',
            field=models.CharField(choices=[('student', 'Student'), ('professor', 'Professor')], default='professor', max_length=20),
        ),
    ]
