# Generated by Django 6.0.6 on 2026-06-03 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0013_pack_target_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='is_public',
            field=models.BooleanField(default=False, help_text='If True, visible to all users. If False, Pro members only.'),
        ),
    ]
