# Generated by Django 6.0.6 on 2026-08-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0017_creditwallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='email',
            field=models.EmailField(blank=True, help_text='Contact email for this gym location', max_length=254),
        ),
        migrations.AddField(
            model_name='region',
            name='location',
            field=models.CharField(blank=True, help_text='Address of this gym location', max_length=255),
        ),
        migrations.AddField(
            model_name='region',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact phone number for this gym location', max_length=30),
        ),
    ]
