# Generated by Django 6.0.6 on 2026-08-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0018_region_email_region_location_region_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='wifi_name',
            field=models.CharField(blank=True, help_text="Guest Wi-Fi network shown on this location's TV screens", max_length=100),
        ),
        migrations.AddField(
            model_name='region',
            name='wifi_password',
            field=models.CharField(blank=True, help_text="Guest Wi-Fi password shown on this location's TV screens", max_length=100),
        ),
    ]
