# Generated by Django 3.2.25 on 2025-09-23 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='zipcode',
        ),
    ]
