# Generated by Django 5.2.9 on 2025-12-04 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_pack_total_hours'),
        ('user', '0003_user_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='remaining_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Remaining hours from subscription', max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='subscribed_pack',
            field=models.ForeignKey(blank=True, help_text='Currently subscribed pack', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscribers', to='subscriptions.pack'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_date',
            field=models.DateTimeField(blank=True, help_text='Date when user last subscribed', null=True),
        ),
    ]
