# Generated by Django 4.2.25 on 2026-01-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='used_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total hours used by the professor for bookings', max_digits=10),
        ),
    ]
