# Generated by Django 4.2.25 on 2026-03-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_purchased_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total hours purchased by the user from all packs', max_digits=10),
        ),
    ]
