# Generated by Django 6.0.6 on 2026-06-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_user_is_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_public',
            field=models.BooleanField(default=False, help_text='True when the student registered themselves'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
    ]
