# Generated by Django 6.0.6 on 2026-06-04 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_student_is_public_alter_user_is_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_public',
            field=models.BooleanField(default=False, help_text='True for professors who self-registered; False for admin-created.'),
        ),
    ]
