# Generated by Django 5.2.11 on 2026-06-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0012_user_add_is_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(
                default=False, help_text="True if student email has been verified"
            ),
        ),
    ]
