# Generated by Django 5.2.11 on 2026-06-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0013_user_is_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="True if student email has been verified",
                null=True,
            ),
        ),
    ]
