# Generated by Django 5.2.11 on 2026-06-09 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0015_student_is_verified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_verified",
        ),
    ]
