# Generated by Django 5.2.11 on 2026-06-09 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0017_emailverificationotp"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailverificationotp",
            name="registration_data",
            field=models.JSONField(
                default=dict, help_text="Store registration data until verification"
            ),
        ),
        migrations.AlterField(
            model_name="emailverificationotp",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_verification_otps",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
