# Generated by Django 6.0.6 on 2026-06-12 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_emailverificationotp_registration_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='professor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'professor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to=settings.AUTH_USER_MODEL),
        ),
    ]
