# Generated by Django 6.0.6 on 2026-06-15 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0016_pack_region'),
        ('user', '0019_student_professor_set_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='region',
            field=models.ForeignKey(blank=True, help_text='Gym region/location this student belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='subscriptions.region'),
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.ForeignKey(blank=True, help_text='Gym region/location this user belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='subscriptions.region'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_public',
            field=models.BooleanField(default=False, help_text='True for public-tier professors (added by admin); False for pro-tier professors (self-registered).'),
        ),
    ]
