# Generated by Django 5.2.15 on 2026-06-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0020_student_region_user_region_alter_user_is_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(
                default=False, help_text="True if user email has been verified"
            ),
        ),
    ]
