# Generated by Django 3.2.25 on 2025-06-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('booking_date', models.DateField()),
                ('time_slot', models.CharField(choices=[('00:00 - 01:00', '00:00 - 01:00'), ('01:00 - 02:00', '01:00 - 02:00'), ('02:00 - 03:00', '02:00 - 03:00'), ('03:00 - 04:00', '03:00 - 04:00'), ('04:00 - 05:00', '04:00 - 05:00'), ('05:00 - 06:00', '05:00 - 06:00'), ('06:00 - 07:00', '06:00 - 07:00'), ('07:00 - 08:00', '07:00 - 08:00'), ('08:00 - 09:00', '08:00 - 09:00'), ('09:00 - 10:00', '09:00 - 10:00'), ('10:00 - 11:00', '10:00 - 11:00'), ('11:00 - 12:00', '11:00 - 12:00'), ('12:00 - 13:00', '12:00 - 13:00'), ('13:00 - 14:00', '13:00 - 14:00'), ('14:00 - 15:00', '14:00 - 15:00'), ('15:00 - 16:00', '15:00 - 16:00'), ('16:00 - 17:00', '16:00 - 17:00'), ('17:00 - 18:00', '17:00 - 18:00'), ('18:00 - 19:00', '18:00 - 19:00'), ('19:00 - 20:00', '19:00 - 20:00'), ('20:00 - 21:00', '20:00 - 21:00'), ('21:00 - 22:00', '21:00 - 22:00'), ('22:00 - 23:00', '22:00 - 23:00'), ('23:00 - 24:00', '23:00 - 24:00')], max_length=20)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='approve', max_length=20)),
                ('approve', models.BooleanField(default=False)),
                ('total_students', models.PositiveIntegerField(default=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['booking_date', 'time_slot'],
            },
        ),
    ]
