# Generated by Django 3.2.25 on 2025-06-30 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='professor',
            field=models.ForeignKey(limit_choices_to={'role__in': ['professor', 'teacher']}, on_delete=django.db.models.deletion.CASCADE, related_name='professor_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='students',
            field=models.ManyToManyField(limit_choices_to={'role': 'student'}, related_name='student_bookings', to='user.Student'),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('booking_date', 'time_slot', 'professor')},
        ),
    ]
