# Generated by Django 3.2.25 on 2025-07-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='students',
            field=models.ManyToManyField(related_name='student_bookings', to='user.Student'),
        ),
    ]
