# Generated by Django 4.2.25 on 2026-02-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='igloo_job_id',
            field=models.CharField(blank=True, help_text='Igloo Job ID for this booking', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='igloo_pin',
            field=models.CharField(blank=True, help_text='Igloo PIN code for this booking', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='pin_type',
            field=models.CharField(choices=[('onetime', 'One-Time'), ('hourly', 'Hourly'), ('permanent', 'Permanent')], default='onetime', help_text='Type of Igloo PIN for this booking', max_length=20),
        ),
    ]
