# Generated by Django 4.2.25 on 2026-02-23 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_igloo_job_id_booking_igloo_pin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='pin_type',
        ),
    ]
