# Generated by Django 6.0.6 on 2026-06-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_remove_booking_pin_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('pro', 'Pro'), ('public', 'Public')], default='pro', max_length=10),
        ),
    ]
