# Generated by Django 6.0.6 on 2026-06-15 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_type'),
        ('subscriptions', '0016_pack_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='region',
            field=models.ForeignKey(blank=True, help_text='Gym region/location for this booking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='subscriptions.region'),
        ),
    ]
